# Generated by Django 5.2 on 2025-04-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_cnpj_customuser_is_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='nome',
        ),
    ]
