# Generated by Django 5.2 on 2025-04-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_company_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
    ]
