# Generated by Django 5.2 on 2025-04-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_company_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nome',
        ),
    ]
